"""Engineering summary generation.

The framework already holds the full engineering record: requirement
analysis, implementation plan with statuses and lineage, approvals, and
the audit history with metrics. This module renders that record into the
final engineering summary document - plan/rationale, artifacts,
execution/reliability, approvals, risks, assumptions, and limitations.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from ai_sdlc.observability.metrics import compute_metrics
from ai_sdlc.state.plan import PlanDocument
from ai_sdlc.workspace import Workspace


def _extract_section(markdown: str, keyword: str) -> str | None:
    """Body of the first ## heading whose title contains keyword."""
    pattern = re.compile(
        rf"(?im)^##[^\n]*{re.escape(keyword)}[^\n]*\n(.*?)(?=^## |\Z)",
        re.DOTALL | re.MULTILINE,
    )
    match = pattern.search(markdown)
    if not match:
        return None
    body = match.group(1).strip()
    return body or None


def _load_events(runs_dir: Path) -> tuple[list[Path], list[dict]]:
    logs = sorted(runs_dir.glob("audit-*.jsonl"))
    events: list[dict] = []
    for log in logs:
        for line in log.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                events.append(json.loads(line))
    return logs, events


def generate_summary(ws: Workspace) -> str:
    lines: list[str] = [
        f"# Engineering Summary: {ws.root.name}",
        "",
        "Generated by ai-sdlc from the project's plan, approvals, and audit history.",
        "",
    ]

    # --- plan and rationale ---
    lines += ["## Plan and Rationale", ""]
    analysis_text = None
    if ws.analysis_path.is_file():
        analysis_text = ws.analysis_path.read_text(encoding="utf-8")
        lines.append(f"- Requirement analysis: {ws.analysis_path.name} (in .ai-sdlc/plan/)")
    else:
        lines.append("- No requirement analysis found")

    tasks = []
    if ws.plan_path.is_file():
        doc = PlanDocument.load(ws.plan_path)
        tasks = doc.tasks
        branch = doc.meta.get("branch")
        if branch:
            lines.append(f"- Working branch: {branch}")
        lines.append(f"- Implementation plan: {len(tasks)} task(s)")
        if tasks:
            lines += ["", "| Task | Title | Persona | Status | Derived from |", "|---|---|---|---|---|"]
            for t in tasks:
                lineage = ", ".join(t.derived_from) or "-"
                lines.append(f"| {t.id} | {t.title} | {t.persona} | {t.status} | {lineage} |")
    else:
        lines.append("- No implementation plan found")
    lines.append("")

    # --- artifacts ---
    artifacts = sorted({a for t in tasks for a in t.artifacts})
    lines += ["## Artifacts", ""]
    if artifacts:
        lines += [f"- {a}" for a in artifacts]
    else:
        lines.append("- Artifacts are tracked per task; see the plan table and per-task commits ([ai-sdlc:<id>] markers) in git history")
    lines.append("")

    # --- execution and reliability ---
    lines += ["## Execution and Reliability", ""]
    by_status: dict[str, int] = {}
    for t in tasks:
        by_status[t.status] = by_status.get(t.status, 0) + 1
    for status in ("completed", "pending", "in_progress", "waiting_approval", "blocked", "rolled_back"):
        if status in by_status:
            lines.append(f"- Tasks {status}: {by_status[status]}")
    logs, events = _load_events(ws.runs_dir)
    lines.append(f"- Recorded runs: {len(logs)}")
    if logs:
        metrics = compute_metrics(logs[-1])
        lines.append(f"- Latest run success rate: {metrics['success_rate'] * 100:.1f}%")
        lines.append(f"- Retries: {sum(1 for e in events if e['type'] == 'retry')}")
        lines.append(f"- Rollbacks: {sum(1 for e in events if e['type'] == 'rollback')}")
        lines.append(f"- Latest run MTTR: {metrics['mttr_seconds']:.1f}s")
        lines.append(f"- Latest run end-to-end: {metrics['e2e_seconds']:.1f}s")
        for stage, seconds in metrics["per_stage_seconds"].items():
            lines.append(f"- Latest run {stage} stage: {seconds:.1f}s")
    lines.append("")

    # --- approvals and decisions ---
    lines += ["## Approvals and Decisions", ""]
    approvals_path = ws.state_dir / "approvals.yaml"
    if approvals_path.is_file():
        approvals = yaml.safe_load(approvals_path.read_text(encoding="utf-8")) or {}
        for gate, value in approvals.items():
            if gate != "analysis_sha":
                lines.append(f"- Approval on record: {gate} = {value}")
    decision_events = [e for e in events if e["type"] in ("approval", "decision", "replan_applied", "push", "rollback")]
    for event in decision_events:
        detail = " ".join(f"{k}={v}" for k, v in event.items() if k not in ("ts", "run_id", "type"))
        lines.append(f"- {event['type']}: {detail}")
    if not decision_events and not approvals_path.is_file():
        lines.append("- None recorded yet")
    lines.append("")

    # --- risks, assumptions ---
    lines += ["## Risks and Trade-offs", ""]
    risks = _extract_section(analysis_text, "risk") if analysis_text else None
    lines.append(risks if risks else "- Not documented (no risk section in the analysis)")
    lines += ["", "## Assumptions", ""]
    assumptions = _extract_section(analysis_text, "assumption") if analysis_text else None
    lines.append(assumptions if assumptions else "- Not documented (no assumptions section in the analysis)")
    lines.append("")

    # --- limitations ---
    lines += ["## Limitations", ""]
    blocked = [t for t in tasks if t.status in ("blocked", "rolled_back")]
    if blocked:
        for t in blocked:
            lines.append(f"- {t.id} ({t.title}) is {t.status}; see audit log for the failure detail")
    pending = [t for t in tasks if t.status == "pending"]
    if pending:
        lines.append(f"- {len(pending)} task(s) not yet executed")
    if not blocked and not pending:
        lines.append("- All planned tasks completed; verify via the project's testing approach before release")
    lines.append("")

    return "\n".join(lines)
